crud/client/urls.py
from django.conf.urls import url
from django.urls.conf import path
from . import views
from .views import *

app_name = "client"

urlpatterns = [
    path("", views.ClientFormView.as_view(), name="client"),
    url(r'^client_list/', client_list, name="client_list"),
    url(r'^client_new/', client_new, name="client_new"),
    url(r'^client_edit/(?P<pk>[0-9]+)', client_edit, name="client_edit"),
    url(r'^client_remove/(?P<pk>[0-9]+)', client_remove, name="client_remove"),

]

crud/crud/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    # Django Admin
    path("admin/", admin.site.urls),
    # User Management
    path("accounts/", include("allauth.urls")),
    # path("", TemplateView.as_view(template_name="account/login.html")),
    # Local
    path("", include("pages.urls", namespace="pages")),
    # Client Urls
    url(r'', include('client.urls')),
]

crud/pages/urls.py
from django.conf.urls import url
from django.urls import path
from allauth.account.views import LoginView, SignupView


from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),

]

crud/client/models.py
from django.db import models
from localflavor.br.forms import BRZipCodeField

# Create your models here.


class Client(models.Model):
    nome = models.CharField(max_length=100)
    telefone = models.CharField(max_length=15)
    cep = models.CharField(max_length=9)
    rua = models.CharField(max_length=100)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=100)
    numero = models.CharField(max_length=10)

crud/pages/models.py
from django.db import models

# Create your models here.

crud/client/forms.py
from django import forms
from localflavor.br.forms import BRZipCodeField


class ClientForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=100)
    cell = forms.CharField(label='Telefone', max_length=11)
    cep = BRZipCodeField(label='CEP', max_length=9)
    rua = forms.CharField(label='Rua', max_length=100)
    bairro = forms.CharField(label='Bairro', max_length=100)
    cidade = forms.CharField(label='Cidade', max_length=100)
    estado = forms.CharField(label='Estado', max_length=100)
    num = forms.CharField(label='Número', max_length=5)

crud/client/views.py
import re
from .models import *
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.forms import ModelForm
from .forms import ClientForm
from django.shortcuts import get_object_or_404, redirect, render


class ClientFormView(FormView):
    form_class = ClientForm
    success_url = reverse_lazy('client:client')
    template_name = 'client/client.html'

# class BaseeView(ListView):
#     queryset = [str(user) for user in User.objects.filter(username)]
#     template_name= 'basee.html'


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ['nome', 'telefone', 'cep', 'rua',
                  'bairro', 'cidade', 'estado', 'numero']


def client_list(request, template_name='client_list.html'):
    client = Client.objects.all()
    clients = {'lista': client}
    return render(request, template_name, clients)


def client_new(request, template_name="client_form.html"):
    form = ClientForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('client:client_list')
    return render(request, template_name, {'form': form})


def client_edit(request, pk, template_name='client_form.html'):
    client = get_object_or_404(Client, pk=pk)
    if request.method == "POST":
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            client = form.save()
            return redirect('client:client_list')
    else:
        form = ClientForm(instance=client)
    return render(request, template_name, {'form': form})


def client_remove(request, pk):
    client = Client.objects.get(pk=pk)
    if request.method == "POST":
        client.delete()
        return redirect('client:client_list')
    return render(request, 'client_delete.html', {'client': client})

crud/pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"

crud/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    
    <meta charset="UTF-8" />
    <title>{% block title %}{% endblock title%}</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-dark bg-dark navblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'pages:home' %}">SNET CRUD</a>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    {% block content %} {% endblock %}

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
    
    <style>
      .navblue {
        background: #074583 !important;
      }
    </style>
  </body>
</html>

crud/templates/client_delete.html
{% extends 'base.html' %}


{% block title %} <h1 class="center">Remoção de cliente </h1>{% endblock title%} 
 
{% block content %}

<form method="POST" class="center">{% csrf_token %}
  <h4>Tem certeza que deseja excluir o cliente "{{ client.nome }}"?</h4>
  <br/>
  <button type="submit" class="center">Remover</button>
</form>

<style>
  .center {
    
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    align-content: center;
  }
  button {
    width: 30%;
    background-color: #074583;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 20px;
  }
  button:hover {
    background-color: #033e7c;
  }
</style>
{% endblock content%}

crud/templates/client_form.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Adicionar cliente</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
      <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>
</head>
    <!-- Adicionando JQuery -->
<script>
  $(document).ready(function() {
    function limpa_formulário_cep() {
      // Limpa valores do formulário de cep.
      $("#rua").val("");
      $("#bairro").val("");
      $("#cidade").val("");
      $("#uf").val("");
      $("#ibge").val("");
    }
     //Quando o campo cep perde o foco.
    $("#id_cep").blur(function() {
      //Nova variável "cep" somente com dígitos.
      var cep = $(this).val().replace(/\D/g, '');
      //Verifica se campo cep possui valor informado.
      if (cep != "") {
        //Expressão regular para validar o CEP.
        var validacep = /^[0-9]{8}$/;
        //Valida o formato do CEP.
        if(validacep.test(cep)) {
          //Preenche os campos com "..." enquanto consulta webservice.
          $("#id_rua").val("...");
          $("#id_bairro").val("...");
          $("#id_cidade").val("...");
          $("#id_estado").val("...");
            //Consulta o webservice viacep.com.br/
            $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {
              if (!("erro" in dados)) {
                //Atualiza os campos com os valores da consulta.
                $("#id_rua").val(dados.logradouro);
                $("#id_bairro").val(dados.bairro);
                $("#id_cidade").val(dados.localidade);
                $("#id_estado").val(dados.uf);   
              } //end if.
              else {
                //CEP pesquisado não foi encontrado.
                limpa_formulário_cep();
                alert("CEP não encontrado.");
              }
            });
        } //end if.
        else {
          //cep é inválido.
          limpa_formulário_cep();
          alert("Formato de CEP inválido.");
        }
      } //end if.
      else {
        //cep sem valor, limpa formulário.
        limpa_formulário_cep();
      }
    });
  });
</script>
{% block content %}   
<p>Cadastro de Clientes</p>
<form method="POST">
{% csrf_token %}
{% bootstrap_form form %}
<button type="submit" class="center">Salvar</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>

<script>
  $(document).ready(function(){
    
    $("#id_cep").mask("00000-000");
    $('#id_telefone').mask('(00) 00000-0000');
  })
</script>
<style>
  * {
    font-family: 'Roboto', sans-serif;
  }

  p {
    font-size: 25px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  input, select, button {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }
  
  .center {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  button {
    
    background-color: #074583;
    color: white;
    padding: 18px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 20px;
  }
  
  button:hover {
    background-color: #033e7c;
  }
  
  body {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
  }
  </style>    
{% endblock content %}

crud/templates/client_list.html
{% extends 'base.html' %} 
 

{% block content %}

<table class="table table-bordered">
  <p class="center">Listagem de clientes</p>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>CEP</th>
    </tr>
  </thead>
  <tbody>
    {% for client in lista %}
    <tr>
      <td>{{client.nome}}</td>
      <td>{{client.telefone}}</td>
      <td>{{client.cep}}</td>
      <td>
        <a href="{% url 'client:client_edit' pk=client.pk %}">
          <span class="fas fa-pen blue"></span>
        </a>
        <a href="{% url 'client:client_remove' pk=client.pk %}">
          <span class="fas fa-trash blue"></span>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<a class="center" href="{% url 'client:client_new' %}">
  <button class="button" type="submit">Cadastrar</button>
</a>

<style>

  p, table {
    margin-top: 50px;
  }  

  tr th {
    margin-left: 10px !important;
  }
  td {
    padding: 25px !important;
  }
  .blue {
    color: #074583;
    font-size: 20px;
  }

  .center {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .button {
    width: 98%;
    background-color: #074583;
    color: white;
    padding: 18px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 20px;
  }
  .button:hover {
    background-color: #033e7c;
  }
  p {
    font-size: 25px;
    display: flex;
    align-items: center;
    justify-content: center;
  }
</style>



{% endblock content%}

crud/templates/home.html
{% extends 'base.html' %}

{% block title %}SNET CRUD{% endblock %}
    
{% block content %}
<p class="center">Faça login para consultar os clientes cadastrados</p>
<style>  
p{
  margin-top: 200px;
  font-size: 25px;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>
{% endblock %}
        
</body>
</html>